"""empty message

Revision ID: fb3bc9f1a888
Revises: 
Create Date: 2023-09-01 16:08:02.549940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3bc9f1a888'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('python_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latest_version', sa.String(length=15), nullable=False),
    sa.Column('approved_version', sa.String(length=15), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('home_page', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_python_requirements_id'), 'python_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_python_requirements_name'), 'python_requirements', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_python_requirements_name'), table_name='python_requirements')
    op.drop_index(op.f('ix_python_requirements_id'), table_name='python_requirements')
    op.drop_table('python_requirements')
    # ### end Alembic commands ###
